version: '3.7'

services:
  search-service:
    image: search-service:latest
    container_name: search-service
    ports:
      - "8081:8081"
    networks:
      - monitoring_network
    depends_on:
      - prometheus

  shop-mock-service:
    image: shop-mock-service:latest
    container_name: shop-mock-service
    ports:
      - "8080:8080"
    networks:
      - monitoring_network
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./src/main/resources/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring_network
    depends_on:
      - grafana

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - monitoring_network

networks:
  monitoring_network:
    driver: bridge
