version: '3.7'

services:
  search-service:
    image: search-service:latest
    container_name: search-service
    ports:
      - "8082:8082"
    networks:
      - monitoring_network
    depends_on:
      - prometheus

  shop-mock-service:
    image: shop-mock-service:latest
    container_name: shop-mock-service
    ports:
      - "8081:8081"
    networks:
      - monitoring_network
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./src/main/resources/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring_network
    depends_on:
      - grafana

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - monitoring_network

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    command:
      - '--housekeeping_interval=10s'
      - '--max_housekeeping_interval=15s'
      - '--allow_dynamic_housekeeping=true'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    restart: unless-stopped


networks:
  monitoring_network:
    driver: bridge
