scrape_configs:
  - job_name: 'prometheus-search-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['search-service:8083']

  - job_name: 'prometheus-shopping-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'shopping-service:8084' ]

  - job_name: 'prometheus-order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'order-service:8085' ]

  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]
