server:
  port: 8081
  error:
    include-message: always
  servlet:
    context-path: /shop-mock-service

external:
  api:
    shop-mock-service:
      url: http://shop-mock-service:8080/products

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.example.shopmockservice: DEBUG