server:
  port: 8081
  error:
    include-message: always
  servlet:
    context-path: /shop-mock-service

external:
  api:
    shop-mock-service:
      url: http://localhost:8080/products

logging:
  level:
    root: INFO
    com.example.shopmockservice: DEBUG