scrape_configs:
  - job_name: 'prometheus-search-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['search-service:8082']

  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]
